/**
 * 自动生成 sidebars.js
 * 扫描 reports 目录，自动添加所有报告到侧边栏
 */

const fs = require('fs');
const path = require('path');

const reportsDir = path.join(__dirname, '..', 'reports');
const sidebarsPath = path.join(__dirname, '..', 'sidebars.js');

function getReportStructure() {
  const structure = {};
  
  if (!fs.existsSync(reportsDir)) {
    console.log('Reports directory not found');
    return null;
  }
  
  const years = fs.readdirSync(reportsDir)
    .filter(f => fs.statSync(path.join(reportsDir, f)).isDirectory())
    .sort().reverse();
  
  for (const year of years) {
    const yearDir = path.join(reportsDir, year);
    structure[year] = {};
    
    const months = fs.readdirSync(yearDir)
      .filter(f => fs.statSync(path.join(yearDir, f)).isDirectory())
      .sort().reverse();
    
    for (const month of months) {
      const monthDir = path.join(yearDir, month);
      const reports = fs.readdirSync(monthDir)
        .filter(f => f.endsWith('.md'))
        .map(f => f.replace('.md', ''))
        .sort().reverse();
      
      if (reports.length > 0) {
        structure[year][month] = reports;
      }
    }
  }
  
  return structure;
}

function getMonthName(month) {
  const names = {'01':'1月','02':'2月','03':'3月','04':'4月','05':'5月','06':'6月',
                 '07':'7月','08':'8月','09':'9月','10':'10月','11':'11月','12':'12月'};
  return names[month] || month;
}

function generateSidebarItems(structure) {
  const items = [];
  
  for (const [year, months] of Object.entries(structure)) {
    const yearItems = [];
    
    for (const [month, reports] of Object.entries(months)) {
      yearItems.push({
        type: 'category',
        label: getMonthName(month),
        items: reports.map(r => `${year}/${month}/${r}`),
      });
    }
    
    yearItems.sort((a, b) => parseInt(b.label) - parseInt(a.label));
    items.push({ type: 'category', label: `${year}年`, items: yearItems });
  }
  
  return items;
}

function main() {
  console.log('🔍 Scanning reports...');
  const structure = getReportStructure();
  
  if (!structure || Object.keys(structure).length === 0) {
    console.log('⚠️ No reports found');
    return;
  }
  
  const sidebarItems = generateSidebarItems(structure);
  const content = `// Auto-generated by generate-sidebar.js
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  reportsSidebar: ${JSON.stringify(sidebarItems, null, 2)},
};
export default sidebars;
`;

  fs.writeFileSync(sidebarsPath, content);
  console.log('✅ Sidebar generated!');
}

main();
